apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "licenses.fullname" . }}
  labels:
    app: {{ template "licenses.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: {{ template "ingressClass" . }}
    {{- if .Values.ingress.authURL }}
    nginx.ingress.kubernetes.io/auth-url: {{ tpl .Values.ingress.authURL . | quote }}
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite (?i)/api/(.*) /$1 break;
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/licenses
            backend:
              serviceName: {{ template "licenses.fullname" . }}
              servicePort: {{ .Values.service.port }}
