kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "licenses.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "licenses.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  # Required for leader election
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - "get"
      - "update"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "licenses.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "licenses.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "licenses.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "licenses.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
  