## Global Docker image registry
## Please, note that this will override the image registry for all the images, including dependencies, configured to use the global value
##
# global:
#   imageRegistry:

## Qlik NATS image version
## ref: https://github.com/qlik-trial/qnatsd
##
image:
  registry: qliktech-docker.jfrog.io
  repository: qnatsd
  tag: 0.3.3
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  pullSecrets:
    - name: artifactory-docker-secret

## NATS replicas
replicaCount: 1

## NATS Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  enabled: false
  fsGroup: 1001
  runAsUser: 1001

## NATS Node selector and tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
##
# nodeSelector: {"beta.kubernetes.io/arch": "amd64"}
# tolerations: []

## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName:

## Pods anti-affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
antiAffinity: soft

## Pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

## Additional pod labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}

## Update strategy, can be set to RollingUpdate or OnDelete by default.
## https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets
statefulset:
  updateStrategy: RollingUpdate
  ## Partition update strategy
  ## https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions
  # rollingUpdatePartition:


## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
# limits:
#   cpu: 500m
#   memory: 512Mi
# requests:
#   cpu: 100m
#   memory: 256Mi

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

## Client Authentication
## ref: https://github.com/nats-io/gnatsd#authentication
##
auth:
  enabled: false
  monitor:
    enabled: false
    user: "delivery-monitor"
    password: password
    permissions:
      publish:
        - "monitor-channel"
        - "_STAN.pub.*.monitor-channel"
        - "_STAN.discover.>"
        - "_STAN.close.>"
        - "_STAN.discover.*.ping"
        - "_STAN.sub.>"
        - "_STAN.unsub.>"
        - "_STAN.subclose.>"
        - "_INBOX.>"
      subscribe:
        - "monitor-channel"
        - "_STAN.acks.>"
        - "_INBOX.>"

  users:
  - user: "nats_client"
    password: T0pS3cr3t

  ## Configuration of users that are authenticated used JWTs
  ## Users can be configured with permissions to allow or deny publish/subscribe access to subjects
  ## ref: https://nats.io/documentation/managing_the_server/authorization/
  ##
  jwtUsers:
    - user: "audit"
      stanPermissions:
        subscribe:
        - "system-events.odag.request"
        - "system-events.engine.app"
        - "system-events.user-session"
        - "system-events.spaces"
        - "system-events.licenses"
        - "system-events.generic-links"
        - "system-events.api-keys"
        - "system-events.user-identity"
        - "system-events.web-security"
        - "system-events.tenants"
        - "system-events.users"
        - "system-events.notification-channel"
    - user: "chronos-worker"
      stanPermissions:
        publish:
        - "chronos-worker.>"
    - user: "data-engineering-exporter"
      stanPermissions:
        subscribe:
        - "system-events.>"
    - user: "edge-auth"
      stanPermissions:
        publish:
        - "system-events.user-session"
        - "system-events.user-identity"
        subscribe:
        - "system-events.users"
        - "system-events.user-session"
        - "system-events.identity-providers"
        - "private.idp-sync"
    - user: "engine"
      stanPermissions:
        publish:
        - "com.qlik.app"
        - "com.qlik.engine.session"
        - "com.qlik.engine.system"
        - "system-events.engine.app"
        - "system-events.engine.session"
        - "system-events.engine.system"
        subscribe:
        - "system-events.engine.app"
    - user: "identity-providers"
      stanPermissions:
        publish:
        - "private.idp-sync"
        - "system-events.identity-providers"
    - user: "invite"
      stanPermissions:
        subscribe:
          - "system-events.users"
        publish:
          - "system-events.invite"
    - user: "nl-parser"
      stanPermissions:
        subscribe:
        - "system-events.engine.app"
    - user: "odag"
      stanPermissions:
        publish:
        - "system-events.odag.request"
        - "odag.>"
        subscribe:
        - "odag.>"
        - "system-events.engine.app"
        - "system-events.reloadResults"
    - user: "qix-data-reload"
      stanPermissions:
        publish:
        - "reload"
        - "system-events.reloadResults"
        subscribe:
        - "reload"
    - user: "resource-library"
      stanPermissions:
        publish:
        - "system-events.resource-library"
    - user: "tenants"
      stanPermissions:
        publish:
        - "system-events.tenants"
        - "system-events.web-integrations"
    - user: "users"
      stanPermissions:
        publish:
        - "system-events.users"
    - user: "api-keys"
      stanPermissions:
        subscribe:
        - "system-events.users"
        publish:
        - "system-events.api-keys"
    - user: "collections"
      stanPermissions:
        publish:
        - "system-events.items"
        subscribe:
        - "system-events.engine.app"
        - "system-events.generic-links"
    - user: "licenses"
      stanPermissions:
        publish:
        - "system-events.licenses"
        subscribe:
        - "system-events.licenses"
    - user: "spaces"
      stanPermissions:
        publish:
        - "system-events.spaces"
        subscribe:
        - "system-events.users"
    - user: "precedents"
      stanPermissions:
        subscribe:
        - "system-events.engine.app"
    - user: "eventing"
      stanPermissions:
        publish:
        - "system-events.notification-request"
        subscribe:
        - "system-events.engine.app"
        - "system-events.spaces"
        - "system-events.web-notifications"
        - "system-events.sharing"
    - user: "qix-sessions"
      stanPermissions:
        subscribe:
        - "system-events.engine.app"
        - "system-events.engine.session"
        - "system-events.engine.system"
        - "system-events.reloadResults"
    - user: "qix-datafiles"
      stanPermissions:
        publish:
        - "system-events.datafiles"
        subscribe:
        - "system-events.engine.app"
        - "system-events.spaces"
    - user: "sharing"
      stanPermissions:
        subscribe:
        - "system-events.engine.app"
        publish:
          - "system-events.notification-request"
          - "system-events.sharing"
          - "system-events.alerting"
    - user: "subscriptions"
      stanPermissions:
        subscribe:
        - "system-events.tenants"
        - "system-events.users"
        - "system-events.spaces"
        - "system-events.engine.app"
    - user: "notification-prep"
      stanPermissions:
        subscribe:
          - "system-events.notification-request"
        publish:
          - "system-events.transport-request"
    - user: "web-notifications"
      stanPermissions:
        subscribe:
          - "system-events.transport-request"
        publish:
          - "system-events.web-notifications"
    - user: "generic-links"
      stanPermissions:
        publish:
          - "system-events.generic-links"
        subscribe:
          - "system-events.users"
    - user: "data-connections"
      stanPermissions:
        subscribe:
        - "system-events.spaces"
    - user: "transport"
      stanPermissions:
        subscribe:
          - "system-events.transport-request"
        publish:
          - "system-events.transport-response"
          - "system-events.notification-request"
          - "system-events.notification-channel"
    - user: "web-security"
      stanPermissions:
        publish:
          - "system-events.web-security"
    - user: "reload-tasks"
      stanPermissions:
        subscribe:
          - "system-events.engine.app"
    - user: "reporting"
      stanPermissions:
        publish:
          - "reporting.>"
    - user: "nl-app-search"
      stanPermissions:
        subscribe:
          - "system-events.engine.app"
          - "system-events.reloadResults"
          - "nl-app-search.>"
        publish:
          - "nl-app-search.>"
    - user: "policy-decisions"
      stanPermissions:
        subscribe:
          - "system-events.spaces"
    - user: "catalog"
      stanPermissions:
        subscribe:
          - "system-events.catalog"
          - "events.catalog"
        publish:
          - "system-events.catalog"
          - "events.catalog"
    - user: "data-condition-evaluator"
      stanPermissions:
        subscribe: []
        publish: []
    - user: "condition-manager"
      stanPermissions:
        publish:
          - "system-events.condition-manager"
## Cluster Authentication
## ref: https://github.com/nats-io/gnatsd#authentication
##
clusterAuth:
  enabled: false
  user: nats_cluster
  # password:
  # token:

## Logging parameters
## ref: https://github.com/nats-io/gnatsd#command-line-arguments
##
debug:
  enabled: false
  trace: false
  logtime: false

## System overrides parameters
## ref: https://github.com/nats-io/gnatsd#configuration-file
##
# maxConnections: 100
# maxControlLine: 512
# maxPayload: 65536
# writeDeadline: "2s"

## Client URL to advertise to other servers
##
clientAdvertise: "{{ .Release.Name }}-nats-client:4222"

## Network pullPolicy
## https://kubernetes.io/docs/concepts/services-networking/network-policies/
##
networkPolicy:
  ## Enable creation of NetworkPolicy resources.
  enabled: false
  ## TODO  remove after merging messaging v3.0.0
  nats:
    enabled: false

  ## The Policy model to apply. When set to false, only pods with the correct
  ## client labels will have network access to the port NATS is listening
  ## on. When true, NATS will accept connections from any source
  ## (with the correct destination port).
  ##
  allowExternal: true
  ## Keys
  keys:
    ## Set keys release name for egress rules
    release: "{{ .Release.Name }}"

## NATS svc used for client connections
## ref: https://github.com/nats-io/gnatsd#running
##
client:
  service:
    ## Kubernetes service type
    type: ClusterIP
    port: 4222
    ## Specify the nodePort value for the LoadBalancer and NodePort service types.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
    ##
    # nodePort:
    ## Provide any additional annotations which may be required. This can be used to
    ## set the LoadBalancer service type to internal only.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
    ##
    annotations: {}
    ## Use loadBalancerIP to request a specific static IP,
    ## otherwise leave blank
    ##
    # loadBalancerIP:
## Kubernetes svc used for clustering
## ref: https://github.com/nats-io/gnatsd#clustering
##
cluster:
  service:
    ## Kubernetes service type
    type: ClusterIP
    port: 6222
    ## Specify the nodePort value for the LoadBalancer and NodePort service types.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
    ##
    # nodePort:
    ## Provide any additional annotations which may be required. This can be used to
    ## set the LoadBalancer service type to internal only.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
    ##
    annotations: {}
    ## Use loadBalancerIP to request a specific static IP,
    ## otherwise leave blank
    ##
    # loadBalancerIP:

  ## Do not advertise known cluster IPs to clients
  ##
  noAdvertise: false

## NATS svc used for monitoring
## ref: https://github.com/nats-io/gnatsd#monitoring
##
monitoring:
  service:
    ## Kubernetes service type
    type: ClusterIP
    port: 8222
    ## Specify the nodePort value for the LoadBalancer and NodePort service types.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
    ##
    # nodePort:
    ## Provide any additional annotations which may be required. This can be used to
    ## set the LoadBalancer service type to internal only.
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
    ##
    ## Annotations for Promethues
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "7777"
    ## Use loadBalancerIP to request a specific static IP,
    ## otherwise leave blank
    ##
    loadBalancerIP:

## Configure the ingress resource that allows you to access the
## NATS Monitoring. Set up the URL
## ref: http://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  enabled: false
  # The list of hostnames to be covered with this ingress record.
  # Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
  - name: nats.local

    ## Set this to true in order to enable TLS on the ingress record
    tls: false

    ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
    tlsSecret: nats.local-tls

    ## Ingress annotations done as key:value pairs
    ## If you're using kube-lego, you will want to add:
    ## kubernetes.io/tls-acme: true
    ##
    ## For a full list of possible ingress annotations, please see
    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
    ##
    ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
    annotations:
    #  kubernetes.io/ingress.class: nginx
    #  kubernetes.io/tls-acme: true

  secrets:
  ## If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate should start with -----BEGIN CERTIFICATE----- or
  ## -----BEGIN RSA PRIVATE KEY-----
  ##
  ## name should line up with a tlsSecret set further up
  ## If you're using kube-lego, this is unneeded, as it will create the secret for you if it is not set
  ##
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  # - name: nats.local-tls
  #   key:
  #   certificate:

# Optional additional arguments
extraArgs:
- --jwt_users_file=/opt/bitnami/nats/users.json
- --jwt_auth_url=http://{{ .Release.Name }}-keys:8080/v1/keys/qlik.api.internal
## for localdev use this configuration instead
# - --jwt_auth_url=http://keys:8080/v1/keys/qlik.api.internal

## Metrics / Prometheus NATS Exporter
##
## ref: https://github.com/nats-io/prometheus-nats-exporter
metrics:
  enabled: false
  image:
    registry: qliktech-docker.jfrog.io
    repository: prometheus-nats-exporter
    tag: 0.3.0
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    pullSecrets:
      - name: artifactory-docker-secret
  ## Metrics exporter resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  # resources: {}
  ## Metrics exporter port
  port: 7777
  ## Metrics exporter annotations
  podAnnotations:
    prometheus.io/scrape: "false"  # prometheus annotations are added on the monitoring service instead
    prometheus.io/port: "7777"
  ## Metrics exporter flags
  args:
    - -connz
    - -routez
    - -subz
    - -varz

sidecars:
## Add sidecars to the pod.
## e.g.
# - name: your-image-name
  # image: your-image
  # imagePullPolicy: Always
  # ports:
  # - name: portname
  #   containerPort: 1234
