{{- define "common.initContainer.tpl" -}}
{{- $root := . -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
name: {{ .container.name }}
image: {{ include "common.image" (set . "container" .container ) }}
{{- $pullPolicy := .Values.image.pullPolicy  }}
{{- if .container }}{{- if .container.image }}{{- if .container.image.pullPolicy }}
  {{- $pullPolicy = .container.image.pullPolicy }}
{{- end }}{{- end }}{{- end }}
imagePullPolicy: {{ $pullPolicy }}
{{- if .container.command }}
command: ["{{ .container.command }}"]
{{- end }}
env:
{{- if eq .container.name "migration" }}
  - name: SERVICE_NAME
    value: {{ .Chart.Name }}
{{- end }}
{{- if or .container.configs .container.secrets }}
{{ include "common.transformers" (set . "container" .container ) | indent 2 }}
{{- end }}
{{ $secrets := .Values.secrets}}
{{- if .container  }}{{- if .container.secrets }}
{{ $secrets = .container.secrets}}
{{- end }}{{- end }}
{{- $hasSecret := false -}}
{{- if $secrets.stringData }}
{{- $hasSecret = true -}}
{{- end }}
{{- if $secrets.data }}
{{- $hasSecret = true -}}
{{- end }}
{{- $hasVolumeMounts := false -}}
{{- if .container  }}{{- if .container.volumeMounts }}
{{- $hasVolumeMounts = true -}}
{{- end -}}{{- end -}}
{{- if or $hasSecret $hasVolumeMounts }}
volumeMounts:
{{- end }}
{{- if $hasSecret }}
{{- if contains $name .Release.Name }}
- name: {{ include "common.fullname" . }}-secrets
  mountPath: "/run/secrets/qlik.com/{{ include "common.fullname" . }}"
  readOnly: true
{{- else }}
- name: {{ include "common.fullname" . }}-secrets
  mountPath: "/run/secrets/qlik.com/{{ include "common.fullname" . }}"
  readOnly: true
- name: {{ .Release.Name }}-secrets
  mountPath: "/run/secrets/qlik.com/{{ .Release.Name }}"
  readOnly: true
{{- end }}
{{- end }}
{{- if $hasVolumeMounts }}
{{- range $key, $val:= .container.volumeMounts }}
{{- if kindIs "map" $val }}
{{- if eq $key "default" }}
{{ include "common.volume.mount" (list (include "common.fullname" $root) $root.container.volumeMounts.mountPath) }}
{{- else }}
{{ include "common.volume.mount" (list (printf "%s-%s" (include "common.fullname" $root) $key) $val) }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- include "common.ca-certificates.volumeMount" . }}
{{- $probes := .Values.probes }}
{{- if .container }}{{- if .container.probes }}
  {{- $probes = .container.probes }}
{{- end }}{{- end }}
{{- if .container  }}{{- if .container.resources  }}
resources:
{{ toYaml .container.resources | indent 2 }}
{{- end -}}{{- end -}}
{{- end -}}
{{- define "common.initContainer" -}}
{{- /* clear new line so indentation works correctly */ -}}
{{- println "" -}}
{{- include "common.util.merge" (append . "common.initContainer.tpl") | indent 8 -}}
{{- end -}}
