{{- define "common.serviceaccount.tpl" -}}
apiVersion: v1
kind: ServiceAccount
{{ template "common.metadata" . }}
{{- end -}}
{{- define "common.serviceaccount" -}}
{{- $top := first . -}}
{{- if ne ($top.Values.rbacEnabled | default false) false -}}
{{- template "common.util.merge" (append . "common.serviceaccount.tpl") -}}
{{- end -}}
{{- end -}}