{{- define "common.statefulset.tpl" -}}
{{- $root := . -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- $releaseName := .Release.Name -}}
apiVersion: apps/v1
kind: StatefulSet
{{ template "common.metadata.workload" . }}
spec:
{{- if .Values.statefulset.replicas}}
  replicas: {{ .Values.statefulset.replicas }}
{{- end}}
  template:
    metadata:
      annotations:
        checksum/configs: {{ (print (include "common.configmap.tpl" .)) | sha256sum }}
        checksum/secrets: {{ (print (include "common.secret.tpl" .)) | sha256sum }}
{{- if .Values.statefulset }}{{- if .Values.statefulset.annotations }}
{{ include "common.annote" (dict "annotations" .Values.statefulset.annotations "root" . ) | indent 8 }}
{{- end }}{{- end }}
      labels:
        app: {{ template "common.name" . }}
        release: {{ .Release.Name | quote }}
{{- if .Values.statefulset }}{{- if .Values.statefulset.labels }}
{{ include "common.labelize" .Values.statefulset.labels | indent 8 }}
{{- end }}{{- end }}
    spec:
{{- if ne (.Values.rbacEnabled | default false) false }}
      serviceAccountName: {{ template "common.fullname" . }}
{{- end }}
{{- if .Values.image }}{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
{{- end }}{{- end }}
      volumes:
{{- if contains $name $releaseName }}
      -
{{ include "common.volume.secret" (list (print (include "common.fullname" .) "-secrets") (include "common.fullname" .)) | indent 8 }}
{{- else }}
      -
{{ include "common.volume.secret" (list (print (include "common.fullname" .) "-secrets") (include "common.fullname" .)) | indent 8 }}
      -
{{ include "common.volume.secret" (list (printf "%s-secrets" (.Release.Name)) (printf "%s" (.Release.Name))) | indent 8 }}
{{- end }}

{{- range $type, $volumes:= .Values.statefulset.volumes }}

{{- if contains "emptyDir" $type -}}
{{- range $name, $volume:= $volumes }}
{{- if $volume.mount }}
      -
{{ include "common.volume.emptydir" (list (printf "%s-%s" (include "common.fullname" $root) $name) (printf "%s-%s" (include "common.fullname" $root) $name)) | indent 8 }}
{{- end }}
{{- end }}
{{- end }}

{{- if contains "hostPath" $type -}}
{{- range $name, $volume:= $volumes }}
      -
{{ include "common.volume.hostpath" (list (printf "%s-%s" (include "common.fullname" $root) $name) $volume) | indent 8 }}
{{- end }}
{{- end }}

{{- if contains "configMap" $type -}}
{{- range $name, $volume:= $volumes }}
      -
{{ include "common.volume.configmap" (list (printf "%s-%s" (include "common.fullname" $root) $name) $volume) | indent 8 }}
{{- end }}
{{- end }}

{{- if contains "secret" $type -}}
{{- range $name, $volume:= $volumes }}
      -
{{ include "common.volume.secret" (list (printf "%s-%s" (include "common.fullname" $root) $name) $volume) | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.configs }}{{- if .Values.configs.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.configs.terminationGracePeriodSeconds }}
{{- end }}{{- end }}
      containers:
      -
{{ include "common.container.tpl" (set . "container" .Values.statefulset.container ) | indent 8 }}
  selector:
    matchLabels:
      app: {{ template "common.name" . }}
      release: {{ .Release.Name }}
{{- end -}}
{{- define "common.statefulset" -}}
{{- $top := first . -}}
{{- if and $top.Values.statefulset }}
{{- template "common.util.merge" (append . "common.statefulset.tpl") -}}
{{- end -}}
{{- end -}}
