{{- define "common.storageclass.tpl" -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name | default (include "common.name" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
provisioner: {{ .Values.storageClass.provisioner }}
{{- if .Values.storageClass.reclaimPolicy }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
{{- end }}
{{- if .Values.storageClass.volumeBindingMode }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
{{- end }}
{{- if .Values.storageClass.allowVolumeExpansion }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
{{- end }}
{{- if .Values.storageClass.parameters }}
parameters:
{{- range $key, $val := .Values.storageClass.parameters }}
  {{ $key }}: {{ $val | quote }}
{{- end}}
{{- end }}
{{- if .Values.storageClass.mountOptions }}
mountOptions:
{{- range .Values.storageClass.mountOptions }}
  - {{ . }}
{{- end }}
{{- end }}
{{- end -}}

{{- define "common.storageclass" -}}
{{- $top := first . -}}
{{- if $top.Values.storageClass -}}
{{- template "common.util.merge" (append . "common.storageclass.tpl") -}}
{{- end -}}
{{- end -}}
