apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdi-mc.fullname" . }}
  labels:
    app: {{ template "bdi-mc.fullname" . }}
    chart: {{ template "bdi-mc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: {{ template "bdi-mc.fullname" . }}
    release: {{ .Release.Name }}
