{{- if .Values.outputcloudgw.enabled }}
{{- if or (eq .Values.sourcecloudgw.gateway "gcs") (eq .Values.outputcloudgw.gateway "gcs") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "gcs-cm"
data:
  credentials.json: {{ .Values.google.credentials | toJson }}
{{- end }}
{{- end }}