apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdi.indexingmanager.fullname" . }}
  labels:
    app: {{ template "bdi.indexingmanager.fullname" . }}
    chart: {{ template "bdi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.indexingmanager.service.type }}
  ports:
    - port: 8080
      targetPort: data
      protocol: TCP
      name: data
    - port: 55020
      targetPort: indexing
      protocol: TCP
      name: indexing
{{- if not (.Values.autostartServices) }}
    - port: 55010
      targetPort: persistence
      protocol: TCP
      name: persistence
    - port: 55057
      targetPort: registry
      protocol: TCP
      name: registry
    {{- if .Values.indexingmanager.service.ssh.enabled }}
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
    {{- end }}
{{- end }}
  selector:
    app: {{ template "bdi.indexingmanager.fullname" . }}
    release: {{ .Release.Name }}
