apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdi.indexer.fullname" . }}
  labels:
    app: {{ template "bdi.indexer.fullname" . }}
    chart: {{ template "bdi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 55040
      targetPort: indexer
      protocol: TCP
      name: indexer
    {{- if not (.Values.autostartServices) }}
    {{- if .Values.indexer.service.ssh.enabled }}
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
    {{- end }}{{- end }}
  selector:
    app: {{ template "bdi.indexer.fullname" . }}
    release: {{ .Release.Name }}
