{{- if .Values.indexingmanager.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "bdi.indexingmanager.fullname" . }}
  labels:
    app: {{ template "bdi.indexingmanager.fullname" . }}
    chart: {{ template "bdi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- range $key, $value := .Values.indexingmanager.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /data
            backend:
              serviceName: {{ template "bdi.indexingmanager.fullname" . }}
              servicePort: data
      {{- if .Values.indexingmanager.ingress.host }}
      host: {{ .Values.indexingmanager.ingress.host }}
      {{- end -}}
  {{- if .Values.indexingmanager.ingress.tls }}
  tls:
{{ toYaml .Values.indexingmanager.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
