apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdi.qslexecutor.fullname" . }}
  labels:
    app: {{ template "bdi.qslexecutor.fullname" . }}
    chart: {{ template "bdi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.qslexecutor.service.type }}
  ports:
    - port: 44000
      targetPort: qslexecutor
      protocol: TCP
      name: qslexecutor
    - port: 54000
      targetPort: qslexecutor-r
      protocol: TCP
      name: qslexecutor-r
{{- if not (.Values.autostartServices) }}
    {{- if .Values.qslexecutor.service.ssh.enabled }}
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
    {{- end }}
{{- end }}    
  selector:
    app: {{ template "bdi.qslexecutor.fullname" . }}
    release: {{ .Release.Name }}
