{{- if .Values.qslmanager.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bdi.qslmanager.fullname" . }}
  labels:
    app: {{ template "bdi.qslmanager.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  certificate: {{ required "'qslmanager.tls.certificate' must be set if TLS is enabled" .Values.qslmanager.tls.certificate | b64enc | quote }}
  key: {{ required "'qslmanager.tls.key' must be set if TLS is enabled" .Values.qslmanager.tls.key | b64enc | quote }}
  {{- if .Values.qslmanager.tls.rootCert }}
  rootCert: {{ .Values.qslmanager.tls.rootCert | b64enc | quote }}
  {{- end }}
{{- end }}
