apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdi.restapi.fullname" . }}
  labels:
    app: {{ template "bdi.restapi.fullname" . }}
    chart: {{ template "bdi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.restapi.service.annotations | indent 4 }}
spec:
  type: {{ .Values.restapi.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: restapi
  selector:
    app: {{ template "bdi.restapi.fullname" . }}
    release: {{ .Release.Name }}
