apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdi.symbolserver.fullname" . }}
  labels:
    app: {{ template "bdi.symbolserver.fullname" . }}
    chart: {{ template "bdi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 55030
      targetPort: symbol
      protocol: TCP
      name: symbol
    {{- if not (.Values.autostartServices) }}
    {{- if .Values.symbolserver.service.ssh.enabled }}
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
    {{- end }}
    {{- end }}
  selector:
    app: {{ template "bdi.symbolserver.fullname" . }}
    release: {{ .Release.Name }}
