{{- if .Values.brokerservice.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "bdi.brokerservice.fullname" . }}
  labels:
    app: {{ template "bdi.brokerservice.fullname" . }}
    chart: {{ template "bdi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      name: {{ template "bdi.brokerservice.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "bdi.brokerservice.fullname" . }}
    spec:
      containers:
      - name: {{ template "bdi.brokerservice.fullname" . }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if and (hasKey .Values.brokerservice "enableFileConnectorService") (.Values.brokerservice.enableFileConnectorService) }}
        command: ["/home/ubuntu/dist/file_connector/abdi_file_connector"]
{{ else }}
        command: ["/home/ubuntu/dist/data_broker/abdi_data_broker"]
{{ end }}
        args:
        - -e
        - "$(HOST_IP)"
        - -r
        - "{{ template "bdi.registry.fullname" . }}"
        - -l
        - "{{.Values.acceptLicense}}"
        ports:
        - containerPort: {{ .Values.brokerservice.containerPort }}
          hostPort: {{ .Values.brokerservice.hostPort }}
        env:
        - name: REGISTRY_URI
          value: "{{ template "bdi.registry.fullname" . }}:55057"
        - name: PERSISTENCE_URI
          value: "{{ template "bdi.persistence.fullname" . }}:55010"
        - name: LOGGING_SETTINGS_FILE
          value: "/etc/config/logging/loggingsettings.json"
        {{- if .Values.pathToIndexingLoggingSettingsFile}}
        - name: LOGGING_SETTINGS_FILE
          value: {{ .Values.pathToIndexingLoggingSettingsFile | quote }}
        {{- end}}
        {{- if .Values.brokerservice }} {{- if .Values.brokerservice.pathToIndexingLoggingSettingsFile}}
        - name: LOGGING_SETTINGS_FILE
          value: {{ .Values.brokerservice.pathToIndexingLoggingSettingsFile | quote }}
        {{- end}} {{- end}}
        {{- include "bdi.cloudSync.exportSettings" . | indent 8 }}
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
          - mountPath: {{ .Values.data.path }}
            name: data-pv
          - mountPath: {{ .Values.output.path }}
            name: output-pv
          - name: logging-volume
            mountPath: /etc/config/logging
      volumes:
        {{- if .Values.data.persistence.enabled }}
        - name: data-pv
          persistentVolumeClaim:
            claimName: {{ .Values.data.persistence.existingClaim | default (include "bdi.data.fullname" .) }}
        {{ else }}
        - name: data-pv
          hostPath:
            path: {{ .Values.data.persistence.folder }}
        {{- end }}
        {{- if .Values.output.persistence.enabled }}
        - name: output-pv
          persistentVolumeClaim:
            claimName: {{ .Values.output.persistence.existingClaim | default (include "bdi.output.fullname" .) }}
        {{ else }}
        - name: output-pv
          hostPath:
            path: {{ .Values.output.persistence.folder }}
        {{- end }}
        - name: logging-volume
          configMap:
            name: {{ template "bdi.brokerservice.logging.fullname" . }}
{{- end }}
