{{- if .Values.cache.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "bdi.cache.fullname" . }}
  labels:
    app: {{ template "bdi.cache.fullname" . }}
    chart: {{ template "bdi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.cache.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "bdi.cache.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bdi.cache.fullname" . }}
        release: {{ .Release.Name }}
      annotations:
{{ toYaml .Values.cache.annotations | indent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      tolerations:
{{ toYaml .Values.cache.tolerations | indent 8 }}
      containers:
        - name: {{ template "bdi.cache.fullname" . }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['sh', '-c']
          args:
            - env > /etc/environment && /usr/sbin/sshd -D
          ports:
            {{- if .Values.cache.service.ssh.enabled }}
            - name: ssh
              containerPort: 22
              protocol: TCP
            {{- end }}
          securityContext:
            privileged: {{ .Values.image.privileged }}
          resources:
{{ toYaml .Values.cache.resources | indent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.data.path }}
              name: data-pv
            - mountPath: {{ .Values.output.path }}
              name: output-pv
            - mountPath: {{ .Values.cache.path }}
              name: cache-pv
      volumes:
        {{- if .Values.data.persistence.enabled }}
        - name: data-pv
          persistentVolumeClaim:
            claimName: {{ .Values.data.persistence.existingClaim | default (include "bdi.data.fullname" .) }}
        {{ else }}
        - name: data-pv
          hostPath:
            path: {{ .Values.data.persistence.folder }}
        {{- end }}
        {{- if .Values.output.persistence.enabled }}
        - name: output-pv
          persistentVolumeClaim:
            claimName: {{ .Values.output.persistence.existingClaim | default (include "bdi.output.fullname" .) }}
        {{ else }}
        - name: output-pv
          hostPath:
            path: {{ .Values.output.persistence.folder }}
        {{- end }}
        - name: cache-pv
          hostPath:
            path: {{ .Values.cache.folder }}
{{- end }}
