apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bdi.cluster.fullname" . }}
data:
  cluster.json: |
    {
      "instances": {
        "indexing": {
          "indexing_manager": {"private_ip": {{- if .Values.autostartServices -}}
          "{{ template "bdi.registry.fullname" . }}"
{{- else -}}
          "{{ template "bdi.indexingmanager.fullname" . }}"
{{- end -}}          
          },
          "symbol_servers": [
            {{- range $i := until (.Values.symbolserver.replicaCount | int) }}
            {"private_ip": "{{ template "bdi.symbolserver.fullname" $ }}-{{ $i }}.{{ template "bdi.symbolserver.fullname" $ }}"}
            {{- if not (eq (add1 $i) ($.Values.symbolserver.replicaCount | int)) }},{{ end }}
            {{- end }}
          ],
          "indexer_servers": [
            {{- range $i := until (.Values.indexer.replicaCount | int) }}
            {"private_ip": "{{ template "bdi.indexer.fullname" $ }}-{{ $i }}.{{ template "bdi.indexer.fullname" $ }}"}
            {{- if not (eq (add1 $i) ($.Values.indexer.replicaCount | int)) }},{{ end }}
            {{- end }}
          ]
        },
        "qsl_processor": {
          "qsl_manager": {"private_ip": "{{ template "bdi.qslmanager.fullname" . }}"},
          "qsl_executor": {"private_ip": "{{ template "bdi.qslexecutor.fullname" . }}"},
          "qsl_workers": [
            {{- range $i := until (.Values.qslworker.replicaCount | int) }}
            {"private_ip": "{{ template "bdi.qslworker.fullname" $ }}-{{ $i }}.{{ template "bdi.qslworker.fullname" $ }}"}
            {{- if not (eq (add1 $i) ($.Values.qslworker.replicaCount | int)) }},{{ end }}
            {{- end }}
          ]
        },
        "rest_service": {"private_ip": "{{ template "bdi.restapi.fullname" . }}"},
        "license": {
          "license_server": {"private_ip": "{{ template "bdi.license.fullname" . }}"}
        },
        "cloud_gateway": {
          {{- if .Values.sourcecloudgw.enabled }}
          "source_data": {"private_ip": "{{ template "bdi.sourcecloudgw.fullname" . }}"},
          {{- end }}
          {{- if .Values.outputcloudgw.enabled }}
          "output": {"private_ip": "{{ template "bdi.outputcloudgw.fullname" . }}"}
          {{- end }}
        }
      },
      "region": ""
    }
