apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdi.license.fullname" . }}
  labels:
    app: {{ template "bdi.license.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: "ClusterIP"
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: {{ template "bdi.license.fullname" . }}
  selector:
    app: {{ template "bdi.license.fullname" . }}
    release: {{ .Release.Name }}
