apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdi.managementconsole.fullname" . }}
  labels:
    app: {{ template "bdi.managementconsole.fullname" . }}
    chart: {{ template "bdi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.managementconsole.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: {{ template "bdi.managementconsole.fullname" . }}
    release: {{ .Release.Name }}
