{{- if .Values.managementconsole.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "bdi.managementconsole.fullname" . }}
  labels:
    app: {{ template "bdi.managementconsole.fullname" . }}
    chart: {{ template "bdi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/keep-alive: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    {{- range $key, $value := .Values.managementconsole.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "bdi.managementconsole.fullname" . }}
              servicePort: http
          - path: /v1
            backend:
              serviceName: {{ template "bdi.restapi.fullname" . }}
              servicePort: http
      {{- if .Values.managementconsole.ingress.host }}
      host: {{ .Values.managementconsole.ingress.host }}
      {{- end -}}
  {{- if .Values.managementconsole.ingress.tls }}
  tls:
{{ toYaml .Values.managementconsole.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
