{{- if .Values.outputcloudgw.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdi.outputcloudgw.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: {{ template "bdi.outputcloudgw.fullname" . }}
    release: {{ .Release.Name }}
{{- end }}
