apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdi.qslmanager.fullname" . }}
  annotations:
  {{- range $key, $value := .Values.qslmanager.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "bdi.qslmanager.fullname" . }}
    chart: {{ template "bdi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.qslmanager.service.annotations | indent 4 }}
spec:
  type: {{ .Values.qslmanager.service.type }}
  ports:
    - port: 55000
      targetPort: external
      protocol: TCP
      name: external
    - port: 55001
      targetPort: internal
      protocol: TCP
      name: internal
    - port: 55002
      targetPort: results
      protocol: TCP
      name: results
    - port: 55003
      targetPort: inf-results
      protocol: TCP
      name: inf-results
    - port: 65000
      targetPort: roaring-1
      protocol: TCP
      name: roaring-1
    - port: 65001
      targetPort: roaring-2
      protocol: TCP
      name: roaring-2
  selector:
    app: {{ template "bdi.qslmanager.fullname" . }}
    release: {{ .Release.Name }}
