apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bdi.qslmanager.fullname" . }}
  labels:
    app: {{ template "bdi.qslmanager.fullname" . }}
    chart: {{ template "bdi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.qslmanager.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "bdi.qslmanager.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bdi.qslmanager.fullname" . }}
        release: {{ .Release.Name }}
      annotations:
{{ toYaml .Values.qslmanager.annotations | indent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.qslmanager.additionalAffinities }}
      affinity:
{{ toYaml .Values.qslmanager.additionalAffinities | indent 8 }}
      {{- end }}
      {{- with .Values.qslmanager.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      tolerations:
{{ toYaml .Values.qslmanager.tolerations | indent 8 }}
      containers:
        - name: {{ template "bdi.qslmanager.fullname" . }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/home/ubuntu/dist/qsl_processor/qsl_processor_tool"]
          args:
          - -m
          - "manager"
          - -a
          - "{{ template "bdi.qslmanager.fullname" . }}"
          - -p
          - "55000"
          - -i
          - "55001"
          - -o
          - "8080"
          - -r
          - "{{ template "bdi.qslexecutor.fullname" . }}"
          - -x
          - "44000"
          - -c
          - "/etc/config/qslmanager.json"
          - -l
          - "{{.Values.acceptLicense}}"
          env:
          - name: KUBERNETES_MODE
            value: "true"
          - name: ACCEPT_QULA
            value: {{ .Values.acceptLicense | quote }}
          - name: REGISTRY_URI
            value: "{{ template "bdi.registry.fullname" . }}:55057"
          - name: PERSISTENCE_URI
            value: "{{ template "bdi.persistence.fullname" . }}:55010"
          - name: QBDI_MIN_SERVICE_COUNT_SYMBOL
            value: {{ .Values.symbolserver.replicaCount | quote }}
          - name: QBDI_STARTUP_VERBOSITY
            value: "1"
          {{- $redis := index .Values "redis-ha" }}
          {{- if $redis.enabled }}
          - name: KVS_HOST
            value: {{ template "bdi.redis.fullname" . }}
          - name: KVS_PORT
            value: {{ $redis.sentinel.port | quote }}
          {{- if and $redis.auth }}
          - name: KVS_AUTH
            valueFrom:
              secretKeyRef:
              {{- if $redis.existingSecret }}
                name: {{ $redis.existingSecret }}
              {{- else }}
                name: {{ template "bdi.redis.fullname" . }}
              {{- end }}
                key: {{ $redis.authKey | quote }}
          {{- end }}
          - name: KVS_MASTER_NAME
            value: {{ $redis.redis.masterGroupName | quote }}
          {{- end }}
          {{- if .Values.qslmanager.resources.requests }}
          {{- if .Values.qslmanager.resources.requests.cpu }}
          - name: QBDI_VCPU_REQUEST
            value: {{ .Values.qslmanager.resources.requests.cpu | default "" | quote }}
          {{- end }}
          {{- if .Values.qslmanager.resources.requests.memory }}
          - name: QBDI_MEMORY_REQUEST
            value: {{ .Values.qslmanager.resources.requests.memory | default "" | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.qslmanager.resources.limits }}
          {{- if .Values.qslmanager.resources.limits.cpu }}
          - name: QBDI_VCPU_LIMIT
            value: {{ .Values.qslmanager.resources.limits.cpu | default "" | quote }}
          {{- end }}
          {{- if .Values.qslmanager.resources.limits.memory }}
          - name: QBDI_MEMORY_LIMIT
            value: {{ .Values.qslmanager.resources.limits.memory | default "" | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.qslmanager.tls.enabled }}
          - name: QSL_MANAGER_TLS_CERT_PATH
            value: "/home/ubuntu/tls"
          {{- end }}
          {{- include "bdi.cloudSync.exportSettings" . | indent 10 }}
          - name: ENABLE_CRASH_DUMP
            value: {{ .Values.enableCrashDumpUpload | quote }}
          ports:
            - name: external
              containerPort: 55000
              protocol: TCP
            - name: internal
              containerPort: 55001
              protocol: TCP
            - name: results
              containerPort: 55002
              protocol: TCP
            - name: inf-results
              containerPort: 55003
              protocol: TCP
            - name: roaring-1
              containerPort: 65000
              protocol: TCP
            - name: roaring-2
              containerPort: 65001
              protocol: TCP
          securityContext:
            privileged: {{ .Values.image.privileged }}
            {{- if .Values.enableCrashDumpUpload }}
            capabilities:
              add:
                - SYS_PTRACE
            {{- end }}
            {{- include "bdi.qsl.commonprobes" (dict "Values" .Values "PortNum" 55001) | indent 10 }}
          resources:
{{ toYaml .Values.qslmanager.resources | indent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.data.path }}
              name: data-pv
            - mountPath: {{ .Values.output.path }}
              name: output-pv
            {{- if .Values.qslmanager.tls.enabled }}
            - mountPath: /home/ubuntu/tls
              name: tls
              readOnly: true
            {{- end }}
            - name: config-volume
              mountPath: /etc/config
      volumes:
        {{- if .Values.data.persistence.enabled }}
        - name: data-pv
          persistentVolumeClaim:
            claimName: {{ .Values.data.persistence.existingClaim | default (include "bdi.data.fullname" .) }}
        {{ else }}
        - name: data-pv
          hostPath:
            path: {{ .Values.data.persistence.folder }}
        {{- end }}
        {{- if .Values.output.persistence.enabled }}
        - name: output-pv
          persistentVolumeClaim:
            claimName: {{ .Values.output.persistence.existingClaim | default (include "bdi.output.fullname" .) }}
        {{ else }}
        - name: output-pv
          hostPath:
            path: {{ .Values.output.persistence.folder }}
        {{- end }}
        - name: config-volume
          configMap:
            name: {{ template "bdi.qsl.config.fullname" . }}

        {{- if .Values.qslmanager.tls.enabled }}
        - name: tls
          secret:
            secretName: {{ template "bdi.qslmanager.fullname" . }}
            defaultMode: 0400
            items:
              - key: certificate
                path: bdi_server_cert.pem
              - key: key
                path: bdi_server_key.pem
              {{- if .Values.qslmanager.tls.rootCert }}
              - key: rootCert
                path: root_cert.pem
              {{- end }}
        {{- end }}
