apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdi.qslworker.fullname" . }}
  labels:
    app: {{ template "bdi.qslworker.fullname" . }}
    chart: {{ template "bdi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 44001
      targetPort: qslworker
      protocol: TCP
      name: qslworker
    - port: 54001
      targetPort: qslworker-r
      protocol: TCP
      name: qslworker-r
  selector:
    app: {{ template "bdi.qslworker.fullname" . }}
    release: {{ .Release.Name }}
