{{- if .Values.sourcecloudgw.enabled }}
{{- if eq .Values.sourcecloudgw.gateway "" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "bdi.sourcecloudgw.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.data.persistence.size | quote }}
{{- end }}
{{- end }}
