apiVersion: v1
appVersion: 0.14.2
description: A NATS Streaming cluster setup
home: https://nats.io/
keywords:
- NATS
- Messaging
- publish
- subscribe
- streaming
- cluster
- persistence
name: nats-streaming
version: 1.0.2
