apiVersion: v1
kind: Service
metadata:
  name: {{ template "nats-streaming.fullname" . }}-monitoring
  labels:
    app: {{ template "nats-streaming.name" . }}
    chart: "{{ template "nats-streaming.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- if .Values.monitoring.service.annotations }}
  annotations:
{{ toYaml .Values.monitoring.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.monitoring.service.type }}
  {{- if and (eq .Values.monitoring.service.type "LoadBalancer") .Values.monitoring.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.monitoring.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: monitoring
      port: {{ .Values.monitoring.service.port }}
      targetPort: monitoring
      {{- if and (eq .Values.monitoring.service.type "NodePort") (not (empty .Values.monitoring.service.nodePort)) }}
      nodePort: {{ .Values.monitoring.service.nodePort  }}
      {{- end }}
  selector:
    app: {{ template "nats-streaming.name" . }}
    release: {{ .Release.Name | quote }}
