apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-nats-secret
data:
  {{ if .Values.auth.enabled }}
  {{ if .Values.auth.user }}
  client-user: {{ print .Values.auth.user | b64enc }}
  client-password: {{ print .Values.auth.password | b64enc }}
  {{ else if .Values.auth.users }}
  client-user: {{ print (index .Values.auth.users 0).user | b64enc }}
  client-password: {{ print (index .Values.auth.users 0).password | b64enc }}
  {{- end -}}
  {{- end -}}
