{{- if or (.Values.networkPolicy.enabled) (index .Values "networkPolicy" "nats" "enabled") }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ template "nats.fullname" . }}"
  labels:
    chart: "{{ template "messaging.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  podSelector:
    matchLabels:
      app: "{{ template "nats.name" . }}"
      release: {{ .Release.Name | quote }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: "{{ template "nats.name" . }}"
            release: {{ .Release.Name | quote }}
      - podSelector:
          matchLabels:
            app: "{{ template "nats-streaming.name" . }}"
            release: {{ .Release.Name | quote }}
    - ports:
      - port: {{ .Values.client.service.port }}
      from:
        - podSelector:
            matchLabels:
              {{ template "nats.fullname" . }}-client: "true"
    - ports:
      - port: {{ .Values.metrics.port }}
  egress:
    - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
    - to:
      - podSelector:
          matchLabels:
            app: "{{ template "nats.name" . }}"
            release: {{ .Release.Name | quote }}
      - podSelector:
          matchLabels:
            app: "keys"
            release: {{ tpl ( .Values.networkPolicy.keys.release ) . | quote }}
{{- end }}
