name: Helm Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add helm repo
        run: |
          helm repo add qlik https://qliktech.jfrog.io/qliktech/qlikhelm --username ${{ secrets.ARTIFACTORY_USERNAME }} --password ${{ secrets.ARTIFACTORY_PASSWORD}}

      - name: Run helm-gh-pages-action
        uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
