name: Helm Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add helm repo
        run: |
          helm init
          helm helm repo add qlik https://qlik-oss.github.io/qabdi/
                                                          
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: ${{ secrets.ACCESS_TOKEN }}
