name: Helm Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run helm-gh-pages-action
        uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
