name: Helm Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        with:
          charts-folder: charts
          access-token: ${{ secrets.ACCESS_TOKEN }}
